# Builds models-all.txt (every static mesh the model viewer exported) for the
# CustomBuilds model browser. Run again after re-exporting in the viewer.
#   .\make-model-list.ps1 [-Viewer <model viewer folder>]
param(
    [string]$Viewer = (Join-Path $PSScriptRoot "..\..\RSDragonwilds-ModelViewer")
)

$json = Join-Path $Viewer "export\models.json"
if (-not (Test-Path $json)) { Write-Error "Not found: $json (export models in the viewer first)"; exit 1 }
$models = (Get-Content $json -Raw | ConvertFrom-Json).Models

function Get-GamePath([string]$p) {
    if ($p.StartsWith('/')) { return $p }
    if ($p -match '^RSDragonwilds/(Content/)?(.*)$') {
        return "/Game/$($Matches[2])"
    }
    return "/$p"
}

function Get-Group([string]$p) {
    $clean = $p.TrimStart('/')
    $parts = [System.Collections.Generic.List[string]]($clean -split '/')
    if ($parts.Count -gt 0) { $parts.RemoveAt($parts.Count - 1) }
    if ($parts.Count -gt 0 -and $parts[0] -eq 'RSDragonwilds') {
        $parts.RemoveAt(0)
        if ($parts.Count -gt 0 -and $parts[0] -eq 'Content') {
            $parts.RemoveAt(0)
        }
    }
    if ($parts.Count -gt 1 -and $parts[1] -eq 'Art') {
        $parts.RemoveAt(1)
    } elseif ($parts.Count -gt 0 -and $parts[0] -eq 'Art') {
        $parts.RemoveAt(0)
    }
    $valid = @($parts | Where-Object { $_ })
    if ($valid.Count -eq 0) { return 'Other' }
    return ($valid[0..([Math]::Min(2, $valid.Count - 1))] -join ' / ')
}

function Get-Pretty([string]$p) {
    $name = ($p -split '/')[-1] -replace '\..*$', ''
    return (($name -replace '^(SM_|SK_)', '') -replace '_', ' ').Trim()
}

$lines = @("# Every static and skeletal mesh from the model viewer export (name, mesh, category).",
           "# Generated by make-model-list.ps1. Do not edit: use models.txt for your own favourites.")
$rows = foreach ($m in $models) {
    if (-not $m.ObjectPath) { continue }
    [pscustomobject]@{ Name = Get-Pretty $m.ObjectPath; Mesh = Get-GamePath $m.ObjectPath; Group = Get-Group $m.ObjectPath }
}
$rows = $rows | Sort-Object Group, Name
foreach ($r in $rows) { $lines += "$($r.Name) | $($r.Mesh) | $($r.Group)" }
$out = Join-Path $PSScriptRoot "models-all.txt"
[IO.File]::WriteAllLines($out, [string[]]$lines, (New-Object Text.UTF8Encoding($false)))
$groups = ($rows | Group-Object Group).Count
Write-Host "Wrote $($rows.Count) models in $groups categories to $out"
